Ecomrce web/basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'
urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add_basket/', views.basket_add, name='basket_add'),
]

Ecomrce web/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Ecommerce Web"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('basket/', include('basket.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecomrce web/store/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static

app_name = 'store'
urlpatterns = [
    path('', views.all_products, name='all_products'),
    path('cate/<slug:anyvariable>', views.category_list, name='category_list'),
    path('product/<str:tittle_slug>', views.product_detail, name='product_list')
]

Ecomrce web/basket/models.py
from django.db import models

# Create your models here.

Ecomrce web/store/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='product_creator', on_delete=models.CASCADE)
    tittle = models.CharField(max_length=255)
    auth = models.CharField(max_length=255, default='admin')
    image = models.ImageField(upload_to='images/', default='images/un.jpg')
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'products'
        ordering = ('-created',)

    def get_absolute_url(self):
        # print("\n\nhksnkns", self.tittle)
        return reverse('store:product_list', args=[self.tittle])

    def __str__(self):
        return self.tittle

Ecomrce web/basket/views.py
from django.shortcuts import render, get_object_or_404
from .basket import Basket
from store.models import Product
from django.http import JsonResponse


# Create your views here.
def basket_summary(request):
    return render(request, 'store/basket/summary.html')


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product, qty)
        basketqty = basket.__len__()
        print("\n\basketqtyn\n", basketqty)

        response = JsonResponse({'qty': basketqty})
        return response

Ecomrce web/store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category


# Create your views here.

# def categories(request):
#     return {
#         'categories': Category.objects.all()
#     }


def all_products(request):
    products = Product.objects.filter(is_active=True)
    # products = Product.objects.all()
    # for i in products:
    #     print("\n\n\print ", i.tittle)
    return render(request, 'store/home.html', {'products': products})


def category_list(request, anyvariable=None):
    category = get_object_or_404(Category, slug=anyvariable)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})


def product_detail(request, tittle_slug):
    # print("\n\n tittle_slug,", tittle_slug)
    product = get_object_or_404(Product, tittle=tittle_slug, in_stock=True)
    return render(request, 'store/products/detail.html', {'product': product})

Ecomrce web/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">

<head>
    <meta charset="utf-8" />
    <title>{% block title %}BookStore{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>
</head

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">BookStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
<!--                        <li class="nav-item active">-->
<!--                            <a class="nav-link" aria-current="page" href="/">Home</a>-->
<!--                        </li>-->
<!--                        <li class="nav-item">-->
<!--                            <a class="nav-link" href="#">Link</a>-->
<!--                        </li>-->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Library
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url "store:all_products" %}">All</a></li>
                                {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
<!--                    <form class="d-flex">-->
<!--                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--                        <button class="btn btn-outline-success" type="submit">Search</button>-->
<!--                    </form>-->
                </div>
                <a type="button" role="button" href="{% url "basket:basket_summary" %}" class="btn btn-outline-secondary">
                {% with total_qty=basket|length %}
                            <div id="basket-qty" class="d-inline-flex">
                                {% if total_qty > 0 %}
                                    {{ total_qty }}
                                {% else %}
                                    0
                                {% endif %}
                            </div>
                        {% endwith %}
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-cart3" viewBox="0 0 16 16">
                            <path
                                d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                        </svg>
                        Basket
                </a>
            </div>
        </nav>
    </header>
    <div id="content">{% block content %} {% endblock %}</div>
</body>
</html>

Ecomrce web/templates/store/basket/summary.html
{% extends "../base.html" %}
{% block tittle %} Baket {% endblock %}
{% block content%}<h1>summary</h1>{% endblock %}

Ecomrce web/templates/store/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}


<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-2">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="h1 fw-bold">Search, Read, Buy, Review</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator,
          etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Make an account</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">All Books</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.tittle }}</a>
              </p>
            </div>
            <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

Ecomrce web/templates/store/products/category.html
{% extends '../base.html'%}
{% load static %}
{% block content %}
<h1>DHRUMIL</h1>
<main>
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">{{category.name|title}}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
          <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">

            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">9min read</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>


</main>

{% endblock %}

Ecomrce web/templates/store/products/detail.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image"
                     src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.author }}</span> (Author)</p>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Hardback</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">£{{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select id="select">
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                </select>

                            </div>
                            <div class="col-6 text-end">
                                <button type="button" id="add-button" value="{{product.id}}"
                                        class="btn btn-secondary btn-sm">Add to
                                    basket
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
               console.log("json". json)
               document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>
{% endblock %}